version: '3'

services:
  sample-lg1-postgresql:
    build: ./postgresql
    environment:
      LANG: "ja_JP.utf8"
      TZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: sampledb
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepass
    ports:
      - "9832:5432"

